### ISSUE TITLE
Picture of the Champions

### ISSUE THREAD

**Issue by Darth-Koopa** [lchmagKekse/TOTK-SaveGame-Editor#23]
![image](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/assets/45894930/0a2452f0-2e6a-4700-a9dd-b17496a44540)
BOTW save data is required to display "Picture of the Champions" in Zelda's House in TOTK, but I started the game without BOTW save data. Can you edit the save data of TOTK to obtain "Picture of the Champions"?

**Comment by Exincracci** [comment]
> ![image](https://user-images.githubusercontent.com/45894930/238114274-0a2452f0-2e6a-4700-a9dd-b17496a44540.png)
> BOTW save data is required to display "Picture of the Champions" in Zelda's House in TOTK, but I started the game without BOTW save data. Can you edit the save data of TOTK to obtain "Picture of the Champions"?

@Darth-Koopa it’s probably possible but I believe it’s yet to be found out how. My recommendation is that you inject a BOTW save that has the picture on the house, because TOTK reads it even after you started the game - unlike your horses on stable.

I say from experience because my BOTW didn’t hang the picture and I was already playing TOTK. I booted up BOTW, put the picture on the wall, opened TOTK and it was there. Time travel paradox shit here lol

**Comment by Darth-Koopa** [comment]
> 

Thanks.
