### ISSUE TITLE
issues report

### ISSUE THREAD

**Issue by Xrui616** [lchmagKekse/TOTK-SaveGame-Editor#3]
Hi bro, there is no error when I open it, but an error is prompted when I add the progress.sav file.

**Comment by Xrui616** [comment]
![image](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/assets/132867473/dc7a5c60-e4f0-4055-a5cc-d13d11a7f783)

**Comment by lchmagKekse** [comment]
It seems like the application doesn't have enough permissions to write to your E: drive.

Put your progress.sav in the same directory as the executable.

If that doesn't work, try to launch the save game editor with administrator permission.

Hope that helps

**Comment by sviplol** [comment]
The latest component of win11 system net has been integrated, but it still cannot work. The administrator reported an error when running it and adding it to the archive file

**Comment by sviplol** [comment]
@lchmagKekse

**Comment by sviplol** [comment]
I even installed Net3.5 4.1, but it still doesn't work. Hahaha, my respected developer brother



[progress.zip](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/files/11433911/progress.zip)

**Comment by lchmagKekse** [comment]
This is a bug on my end. The savefile shows that you never picked up a bow or a shield so the editor didnt find the offset.

I modified your savefile a bit so the editor can find the correct offsets:
[progress.zip](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/files/11434459/progress.zip)

Also there was a little bug with the sword offset.
Should be fixed with this: https://github.com/lchmagKekse/TOTK-SaveGame-Editor/releases/tag/v1.1.1

**Comment by sviplol** [comment]
@lchmagKekse Dear author. The saved file you have modified will not cause an error when I load it, but when I try to load my own game save file, I will cause an error, and when I load a perfect save file shared by others on the network, I will also cause an error. After this error is reported, I will be unable to modify it. Can we continue to optimize? Thank you very much for your hard work

**Comment by sviplol** [comment]
For detailed information on calling real-time (JIT) debugging instead of this dialog box,
Please refer to the end of this message.
**************Exception Text**************
System. ArgumentOutOfRangeException: Number is less than the lower limit of the array in the first dimension.
Parameter name: srcIndex
In System. Array. Copy (Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean relative)
At TOTK_ SaveGame_ Editor.SaveFile.ReadString(Int32 offset)
At TOTK_ SaveGame_ Editor.MainWindow.SetValuesFromSavefile()
At TOTK_ SaveGame_ Editor.MainWindow.BtnOpenSaveFile_ Click(Object sender, EventArgs e)
In System. Windows. Forms. Control. OnClick (EventArgs e)
In System. Windows. Forms. Button. OnClick (EventArgs e)
In System. Windows. Forms. Button. OnMouseUp (MouseEventArgs mevent)
In System. Windows. Forms. Control. WmMouseUp (Message&m, MouseButtons button, Int32 clicks)
In System. Windows. Forms. Control. WndProc (Message&m)
In System. Windows. Forms. ButtonBase. WndProc (Message&m)
In System. Windows. Forms. Button. WndProc (Message&m)
In System. Windows. Forms. Control. ControlNativeWindow. OnMessage (Message&m)
In System. Windows. Forms. Control. ControlNativeWindow. WndProc (Message&m)
In System. Windows. Forms. NativeWindow. Callback (IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
**************Loaded Assembly**************
mscorlib
Assembly version: 4.0.0.0
Win32 version: 4.8.9139.0 build by: NET481RELLAST_ B
Basic code: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TOTK-SaveGame-Editor
Assembly version: 1.0.0.0
Win32 version: 1.0.0.0
Basic code: file:///C:/Users/svipl/Downloads/Programs/TOTK -SaveGame-Editor.exe
----------------------------------------
System.Windows.Forms
Assembly version: 4.0.0.0
Win32 version: 4.8.9075.0 build by: NET481RELLAST_ C
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
Assembly version: 4.0.0.0
Win32 version: 4.8.9139.0 build by: NET481RELLAST_ B
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
Assembly version: 4.0.0.0
Win32 version: 4.8.9032.0 build by: NET481REL1
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
Assembly version: 4.0.0.0
Win32 version: 4.8.9032.0 build by: NET481REL1
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
Assembly version: 4.0.0.0
Win32 version: 4.8.9139.0 build by: NET481RELLAST_ B
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
Assembly version: 4.0.0.0
Win32 version: 4.8.9032.0 build by: NET481REL1
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
Assembly version: 4.0.0.0
Win32 version: 4.8.9032.0 build by: NET481REL1
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
Assembly version: 4.0.0.0
Win32 version: 4.8.9032.0 build by: NET481REL1
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh -Hans_ b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
Assembly version: 4.0.0.0
Win32 version: 4.8.9032.0 build by: NET481REL1
Basic code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh -Hans_ b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
**************JIT debugging**************
To enable real-time (JIT) debugging,
The system. windows. forms section of the application or computer's. config file (machine. config) must be set to
JitDebugging value.
When compiling an application, it must also be enabled
Debugging.
For example:
<configuration>
<system.windows.forms jitDebugging="true" />
</configuration>
Any unhandled exceptions after enabling JIT debugging
Will be sent to the JIT debugging program registered on this computer,
Instead of handling it through this dialog box.

**Comment by sviplol** [comment]
I saw your message. Is it because my save is too new that the character lacks weapons and shields, so I reported an error? Can we not detect these two points

@lchmagKekse

**Comment by lchmagKekse** [comment]
Yes the save is too new. If you pick up a shield, bow, armor and a sword your can edit the save.
I will try to find a solution that doesnt require me to hardcode offsets.
