### ISSUE TITLE
Adding things to the editor

### ISSUE THREAD

**Issue by Karlos007** [lchmagKekse/TOTK-SaveGame-Editor#5]
Not an issue but I wanted to add more offsets to this program, is it possible?

For example the pouch size for bows shields and weapons (00047634 / 0004D084 / 0004AA68)

And weapon bonuses is also interesting.

**Comment by lchmagKekse** [comment]
Yes, sure it is possible. 
I will try them and add them if they work.
Thanks for your contribution <3

**Comment by impeeza** [comment]
Any way to put a "table" with community finding offsets?  or the use of a database as config for editor?

**Comment by lchmagKekse** [comment]
@Karlos007
The 1.1.0 Update changes some of the offsets thats why i implemented pattern scanning but it seems like that i causing some [issues](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/issues/6) too

**Comment by Karlos007** [comment]
> @Karlos007 The 1.1.0 Update changes some of the offsets thats why i implemented pattern scanning but it seems like that i causing some [issues](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/issues/6) too

If you need help with testing let me know.
The editor is very cool and easy to use.

**Comment by Exincracci** [comment]
> > @Karlos007 The 1.1.0 Update changes some of the offsets thats why i implemented pattern scanning but it seems like that i causing some [issues](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/issues/6) too
> 
> If you need help with testing let me know. The editor is very cool and easy to use.

I agree with Karlos, excellent work! I am around to help with whatever I can. I plan to try matching some other inventory items with their ID today as well.

**Comment by Exincracci** [comment]
@lchmagKekse here's the table for the important items (the star menu)

<html>
<body>

String | Name
-- | --
CaveMasterMedal | Bubbul Gem
Energy_Material_01 | Crystallized Charge
Energy_Material_03 | Large Crystallized Charge
Energy_Material_04 | Huge Crystallized Charge
GameRomHorseReins_01 | Traveler's Bridle
GameRomHorseReins_02 | Royal Bridle
GameRomHorseSaddle_01 | Traveler's Saddle
GameRomHorseSaddle_02 | Royal Saddle
GameRomHorseSaddle_07 | Towing Harness
MinusRupee_00 | Poe
Obj_AutoBuilder | Autobuild
Obj_AutoBuilderDraft_00 | Schema Stone
Obj_Battery_Get | Energy Cell
Obj_Battery_Get_Capacity03 | Energy Cell
Obj_Battery_Get_Capacity04 | Energy Cell
Obj_Battery_Get_Capacity05 | Energy Cell
Obj_Battery_Get_Capacity06 | Energy Cell
Obj_Battery_Get_Capacity07 | Energy Cell
Obj_Battery_Get_Capacity08 | Energy Cell
Obj_Battery_Get_Capacity09 | Energy Cell
Obj_Battery_Get_Capacity10 | Energy Cell
Obj_Battery_Get_Capacity11 | Energy Cell
Obj_Battery_Get_Capacity12 | Energy Cell
Obj_Battery_Get_Capacity13 | Energy Cell
Obj_Battery_Get_Capacity14 | Energy Cell
Obj_Battery_Get_Capacity15 | Energy Cell
Obj_Battery_Get_Capacity16 | Energy Cell
Obj_Battery_Get_Capacity17 | Energy Cell
Obj_Battery_Get_Capacity18 | Energy Cell
Obj_Battery_Get_Capacity19 | Energy Cell
Obj_Battery_Get_Capacity20 | Energy Cell
Obj_Battery_Get_Capacity21 | Energy Cell
Obj_Battery_Get_Capacity22 | Energy Cell
Obj_Battery_Get_Capacity23 | Energy Cell
Obj_Battery_Get_Capacity24 | Energy Cell
Obj_Battery_Get_Capacity25 | Energy Cell
Obj_Battery_Get_Capacity26 | Energy Cell
Obj_Battery_Get_Capacity27 | Energy Cell
Obj_Battery_Get_Capacity28 | Energy Cell
Obj_Battery_Get_Capacity29 | Energy Cell
Obj_Battery_Get_Capacity30 | Energy Cell
Obj_Battery_Get_Capacity31 | Energy Cell
Obj_Battery_Get_Capacity32 | Energy Cell
Obj_Battery_Get_Capacity33 | Energy Cell
Obj_Battery_Get_Capacity34 | Energy Cell
Obj_Battery_Get_Capacity35 | Energy Cell
Obj_Battery_Get_Capacity36 | Energy Cell
Obj_Battery_Get_Capacity37 | Energy Cell
Obj_Battery_Get_Capacity38 | Energy Cell
Obj_Battery_Get_Capacity39 | Energy Cell
Obj_Battery_Get_Capacity40 | Energy Cell
Obj_Battery_Get_Capacity41 | Energy Cell
Obj_Battery_Get_Capacity42 | Energy Cell
Obj_Battery_Get_Capacity43 | Energy Cell
Obj_Battery_Get_Capacity44 | Energy Cell
Obj_Battery_Get_Capacity45 | Energy Cell
Obj_Battery_Get_Capacity46 | Energy Cell
Obj_Battery_Get_Capacity47 | Energy Cell
Obj_Battery_Get_Capacity48 | Energy Cell
Obj_Camera | Camera
Obj_DRStone_Get | Purah Pad
Obj_DungeonClearSeal | Light of Blessing
Obj_HiddenScroll_00 | Earthwake Manual
Obj_KoroNuts | Korok Seed
Obj_OneTouchBond | Fuse
Obj_ProofKorok | Hestu's Gift
Obj_SageSoul_Gerudo | Solemn Vow of Riju, Sage of Fire
Obj_SageSoul_Goron | Solemn Vow of Yunobo, Sage of Fire
Obj_SageSoul_Rito | Solemn Vow of Tulin, Sage of Wind
Obj_SageSoul_Zonau | Solemn Vow of Minuru, Sage of Spirit
Obj_SageSoul_Zora | Solemn Vow of Sidon, Sage of Fire
Obj_SageWill | Sage's Will
Obj_StableHostlePointCard | Pony Points Card
Obj_Tooreroof | Ascend
Obj_TreasureMap_00 | Old Map
Obj_UltraHand | Ultrahand
Obj_WarpDLC_Prototype | Travel Medallion
Parasail | Paraglider


</body>
</html>

**Comment by Exincracci** [comment]
@lchmagKekse here's the table for the important itens (star menu). An important thing to notice is that the Fabrics for the paraglider are removed from the inventory if you talk to the guy at Hateno. He likes kinda takes them so they are available to customize. 

Also, I was able to check some of these things because someone kindly provided a "complete" save with the important items there. It's not totally complete though, I had some things checked with my personal save and the game files to match, but it's pretty useful to check offset and addresses probably: https://github.com/marcrobledo/savegame-editors/issues/164#issuecomment-1542747784

<html>
<body>

String | Name
-- | --
CaveMasterMedal | Bubbul Gem
Energy_Material_01 | Crystallized Charge
Energy_Material_03 | Large Crystallized Charge
Energy_Material_04 | Huge Crystallized Charge
GameRomHorseReins_01 | Traveler's Bridle
GameRomHorseReins_02 | Royal Bridle
GameRomHorseSaddle_01 | Traveler's Saddle
GameRomHorseSaddle_02 | Royal Saddle
GameRomHorseSaddle_07 | Towing Harness
MinusRupee_00 | Poe
Obj_AutoBuilder | Autobuild
Obj_AutoBuilderDraft_00 | Schema Stone
Obj_Battery_Get | Energy Cell
Obj_Battery_Get_Capacity03 | Energy Cell
Obj_Battery_Get_Capacity04 | Energy Cell
Obj_Battery_Get_Capacity05 | Energy Cell
Obj_Battery_Get_Capacity06 | Energy Cell
Obj_Battery_Get_Capacity07 | Energy Cell
Obj_Battery_Get_Capacity08 | Energy Cell
Obj_Battery_Get_Capacity09 | Energy Cell
Obj_Battery_Get_Capacity10 | Energy Cell
Obj_Battery_Get_Capacity11 | Energy Cell
Obj_Battery_Get_Capacity12 | Energy Cell
Obj_Battery_Get_Capacity13 | Energy Cell
Obj_Battery_Get_Capacity14 | Energy Cell
Obj_Battery_Get_Capacity15 | Energy Cell
Obj_Battery_Get_Capacity16 | Energy Cell
Obj_Battery_Get_Capacity17 | Energy Cell
Obj_Battery_Get_Capacity18 | Energy Cell
Obj_Battery_Get_Capacity19 | Energy Cell
Obj_Battery_Get_Capacity20 | Energy Cell
Obj_Battery_Get_Capacity21 | Energy Cell
Obj_Battery_Get_Capacity22 | Energy Cell
Obj_Battery_Get_Capacity23 | Energy Cell
Obj_Battery_Get_Capacity24 | Energy Cell
Obj_Battery_Get_Capacity25 | Energy Cell
Obj_Battery_Get_Capacity26 | Energy Cell
Obj_Battery_Get_Capacity27 | Energy Cell
Obj_Battery_Get_Capacity28 | Energy Cell
Obj_Battery_Get_Capacity29 | Energy Cell
Obj_Battery_Get_Capacity30 | Energy Cell
Obj_Battery_Get_Capacity31 | Energy Cell
Obj_Battery_Get_Capacity32 | Energy Cell
Obj_Battery_Get_Capacity33 | Energy Cell
Obj_Battery_Get_Capacity34 | Energy Cell
Obj_Battery_Get_Capacity35 | Energy Cell
Obj_Battery_Get_Capacity36 | Energy Cell
Obj_Battery_Get_Capacity37 | Energy Cell
Obj_Battery_Get_Capacity38 | Energy Cell
Obj_Battery_Get_Capacity39 | Energy Cell
Obj_Battery_Get_Capacity40 | Energy Cell
Obj_Battery_Get_Capacity41 | Energy Cell
Obj_Battery_Get_Capacity42 | Energy Cell
Obj_Battery_Get_Capacity43 | Energy Cell
Obj_Battery_Get_Capacity44 | Energy Cell
Obj_Battery_Get_Capacity45 | Energy Cell
Obj_Battery_Get_Capacity46 | Energy Cell
Obj_Battery_Get_Capacity47 | Energy Cell
Obj_Battery_Get_Capacity48 | Energy Cell
Obj_Camera | Camera
Obj_DRStone_Get | Purah Pad
Obj_DungeonClearSeal | Light of Blessing
Obj_HiddenScroll_00 | Earthwake Manual
Obj_KoroNuts | Korok Seed
Obj_OneTouchBond | Fuse
Obj_ProofKorok | Hestu's Gift
Obj_SageSoul_Gerudo | Solemn Vow of Riju, Sage of Fire
Obj_SageSoul_Goron | Solemn Vow of Yunobo, Sage of Fire
Obj_SageSoul_Rito | Solemn Vow of Tulin, Sage of Wind
Obj_SageSoul_Zonau | Solemn Vow of Minuru, Sage of Spirit
Obj_SageSoul_Zora | Solemn Vow of Sidon, Sage of Fire
Obj_SageWill | Sage's Will
Obj_StableHostlePointCard | Pony Points Card
Obj_SubstituteCloth_00 | Goron Fabric
Obj_SubstituteCloth_01 | Zora Fabric
Obj_SubstituteCloth_02 | Gerudo Fabric
Obj_SubstituteCloth_03 | Royal Hyrulean Fabric
Obj_SubstituteCloth_05 | Sheikah Fabric
Obj_SubstituteCloth_06 | Yiga Fabric
Obj_SubstituteCloth_07 | Compass Fabric
Obj_SubstituteCloth_08 | Compass Fabric
Obj_SubstituteCloth_09 | Horse-God Fabric
Obj_SubstituteCloth_10 | Fish Fabric
Obj_SubstituteCloth_11 | Lucky Clover Gazette Fabric
Obj_SubstituteCloth_12 | Bolson Fabric
Obj_SubstituteCloth_13 | Mystic Fabric
Obj_SubstituteCloth_14 | Korok Fabric
Obj_SubstituteCloth_15 | Grizzlemaw-Bear Fabric
Obj_SubstituteCloth_16 | Robbie's Fabric
Obj_SubstituteCloth_17 | Cece Fabric
Obj_SubstituteCloth_18 | Aerocuda Fabric
Obj_SubstituteCloth_19 | Eldin-Ostrich Fabric
Obj_SubstituteCloth_20 | Cucco Fabric
Obj_SubstituteCloth_21 | Horse Fabric
Obj_SubstituteCloth_22 | Chuchu Fabric
Obj_SubstituteCloth_23 | Lynel Fabric
Obj_SubstituteCloth_24 | Gleeok Fabric
Obj_SubstituteCloth_25 | Stalnox Fabric
Obj_SubstituteCloth_26 | Tunic of Memories Fabric
Obj_SubstituteCloth_27 | Hylian-Hood Fabric
Obj_SubstituteCloth_28 | Hyrule-Princess Fabric
Obj_SubstituteCloth_29 | Goron-Champion Fabric
Obj_SubstituteCloth_30 | Rito-Champion Fabric
Obj_SubstituteCloth_31 | Zora-Champion Fabric
Obj_SubstituteCloth_32 | Gerudo-Champion Fabric
Obj_SubstituteCloth_33 | Ancient-Sheikah Fabric
Obj_SubstituteCloth_34 | Bokoblin Fabric
Obj_SubstituteCloth_35 | Demon King
Obj_SubstituteCloth_36 | King of Red Lions Fabric
Obj_SubstituteCloth_37 | Sheik Fabric
Obj_SubstituteCloth_38 | Mirror of Twilight Fabric
Obj_SubstituteCloth_39 | Princess of Twilight Fabric
Obj_SubstituteCloth_40 | Lon Lon Ranch Fabric
Obj_SubstituteCloth_41 | Majora's Mask Fabric
Obj_SubstituteCloth_43 | Bygone-Royal Fabric
Obj_SubstituteCloth_45 | Sword-Spirit Fabric
Obj_SubstituteCloth_49 | Goddess Fabric
Obj_SubstituteCloth_51 | Champion's Leathers Fabric
Obj_SubstituteCloth_52 | Princess Zelda Fabric
Obj_SubstituteCloth_53 | Gerudo King Fabric
Obj_SubstituteCloth_55 | Nostalgic Fabric
Obj_SubstituteCloth_56 | Addison's Fabric
Obj_SubstituteCloth_Default | Ordinary Fabric
Obj_Tooreroof | Ascend
Obj_TreasureMap_00 | Old Map
Obj_UltraHand | Ultrahand
Obj_WarpDLC_Prototype | Travel Medallion
Parasail | Paraglider


</body>
</html>

**Comment by Karlos007** [comment]
@lchmagKekse This is all I have for v1.0.0, hope it helps

The coolest thing is to put Attack ++ on weapons
Also durability is not like botw,  999999 does nothing but reseting the durability to the legit max value once you equip it

[TotK_Save_Offsets.xlsx](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/files/11448820/TotK_Save_Offsets.xlsx)

**Comment by Exincracci** [comment]
@lchmagKekse you should a look at this list, very well done and probably helpful: https://docs.google.com/spreadsheets/d/1N1Ty9Wanh2ekUOUIrBFjA9gQVivmHvZtzgBwrPMqwAI/edit#gid=114269320

It was made by [Echocolat](https://github.com/Echocolat).

**Comment by Exincracci** [comment]
@lchmagKekse recommenting with the updated link for table made by [Echocolat](https://github.com/marcrobledo/savegame-editors/issues/164#issuecomment-1544565658)

https://docs.google.com/spreadsheets/d/18pNtDx3z-8CwGJRmlW574xbQ6VphQOkvpZhClpOEVDA/

Taking a quick look, it's possible to notice that our previous weapon list seems to be incomplete. There are items such as "Dusk Bow" (Weapon_Bow_072) for example that are not in the Editor database, so it displays as None. Other amiibo items share this.

**Comment by JonJaded** [comment]
Does anyone know where the offsets are for the horses? My first, main save didn't have my botw horses carry over but now I have a fresh save that has the ported horses. Any way to just copy and paste them in hex?

**Comment by pparmy** [comment]
> Does anyone know where the offsets are for the horses? My first, main save didn't have my botw horses carry over but now I have a fresh save that has the ported horses. Any way to just copy and paste them in hex?
> 
> I'm sure in due time, we'll get horse creating though!

same, I think they only transfer at the beginning of a new game unfortunately - but not certain. Tell me if you ever find a fi x !

**Comment by Karlos007** [comment]
> Does anyone know where the offsets are for the horses? My first, main save didn't have my botw horses carry over but now I have a fresh save that has the ported horses. Any way to just copy and paste them in hex?
> 
> I'm sure in due time, we'll get horse creating though!

The names are 0x10B0CC at least in v1.0.0.
However I can't find the stats type of horse.

**Comment by pparmy** [comment]
> > Does anyone know where the offsets are for the horses? My first, main save didn't have my botw horses carry over but now I have a fresh save that has the ported horses. Any way to just copy and paste them in hex?
> > I'm sure in due time, we'll get horse creating though!
> 
> The names are 0x10B0CC at least in v1.0.0. However I can't find the stats type of horse.

Sorry for the inconvience but how do I edit any data relating to the horses? Like within the save editor if that makes sense,
